
# we are printing car models

print("BMW")
print("mercedes")
print("ferrarai")
print("audi")
print("opel")
print("toyota")
print("porche")
print("nisan")
print("ford")
print("cherlovet")
print("honda")
print("jeep")
print("tesla")
print("hyundai")
print("subaru")
print("kia")
print("Volkswagen ")
print("mazda")
print("fiat")
print("bugati")
print("Porsche")